remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [Jonathan Hales]
description: [Software Engineer working at PostEra.ai to accelerate small molecule drug discovery]
logo: /assets/img/profile.jpeg

